### PR TITLE
Fix/penalty fees sharing

### LINKED ISSUE #149: Penalty fees can be shared among future farms or expired farms, risks of exploits
If you want to report a security issue, please follow our security policy: `https://github.com/MANTRA-Chain/mantra-dex/blob/main/docs/SECURITY.md`

---

## Steps to Reproduce

https://code4rena.com/evaluate/2024-11-mantra-dex/findings/F-6

1. Execute `X` transaction on the `pool-manager` contract 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

---

### Additional context

Add any other context about the problem here, code snippets, json responses and so on.

<details>
<summary>Code sample</summary>

```rust

```

</details>

<details>
  <summary>Logs</summary>

```

```

</details>

### PR DESCRIPTION
**Pull request by mantricjavier**
## Description and Motivation

Fixes #149 .

## Related Issues

---

## Checklist:

- [x] I have read [MANTRA's contribution guidelines](https://github.com/MANTRA-Chain/mantra-dex/blob/main/docs/CONTRIBUTING.md).
- [x] My pull request has a sound title and description (not something vague like `Update index.md`)
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation.
- [x] The code is formatted properly `just fmt`.
- [x] Clippy doesn't report any issues `just lint`.
- [x] I have regenerated the schemas if needed with `just schemas`.

## Summary by CodeRabbit

- **New Features**
  - The withdrawal process has been enhanced to ensure that only eligible, active positions participate in penalty fee distribution during emergency operations.
  - A new method for instantiating the farm manager with a longer epoch buffer has been added, providing more flexibility in testing environments.

- **Tests**
  - Updated emergency withdrawal test case to reflect new penalty distribution logic based on farm activity.
  - Adjusted balance assertions for both creator and fee collector to align with the updated penalty fee structure.

### CODE REVIEW

File: contracts/farm-manager/src/position/commands.rs [hunk 1]
```diff
@@ -339,14 +339,27 @@ pub(crate) fn withdraw_position(
...
         let farms = get_farms_by_lp_denom(
             deps.storage,
             &position.lp_asset.denom,
             None,
             Some(MAX_FARMS_LIMIT),
-        )?;
+        )?
+        .into_iter()
+        // filter out farms that are not active, i.e. have not started yet or have expired
+        .filter(|farm| {
```
Comment (mantricjavier) [inline contracts/farm-manager/src/position/commands.rs:358]: Filter out inactive farms

File: contracts/farm-manager/tests/common/suite.rs [hunk 2]
```diff
@@ -153,6 +153,35 @@ impl TestingSuite {
...
+        self.instantiate(
+            self.fee_collector_addr.to_string(),
+            self.epoch_manager_addr.to_string(),
+            self.pool_manager_addr.to_string(),
+            Coin {
+                denom: "uom".to_string(),
+                amount: Uint128::new(1_000u128),
+            },
+            2,
+            40,
```
Comment (mantricjavier) [inline contracts/farm-manager/tests/common/suite.rs:175]: Changes the max_epoch_buffer property to 40 to be able to accurately test the new change

File: contracts/farm-manager/src/position/commands.rs [hunk 3]
```diff
@@ -339,14 +339,27 @@ pub(crate) fn withdraw_position(
...
+            farm.start_epoch <= current_epoch.id
+                && !is_farm_expired(farm, deps.as_ref(), &env, &config).unwrap_or(false)
+        })
+        .collect::<Vec<_>>();
```
[the remark this answers is not in the document]
Comment (mantricjavier) [reply contracts/farm-manager/src/position/commands.rs:362]: This is safe because the only way is_farm_expired can fail is when querying the current epoch from the epoch manager, which would fail anyway a couple of lines above this code.

**Review by desamtralized — DISMISSED** [review]

**Review by desamtralized — APPROVED** [review]
